In [1]:
# Scratch for collateral calculations (all in main function now)
import numpy as np


In [383]:
# ind2vec
def ind2vec(ind, N=None):
    ind = np.asarray(ind)
    if N is None: 
        N = ind.max() + 1
    return (np.arange(N) == ind[:,None]).astype(int)

In [413]:


def checkCollateral(p_, q_, mInd_, tInd_, p, q, mInd, tInd, iMatched, M):
    # p_, q_, mInd_, tInd_ - New trade
    # p, q, mInd, tInd - Existing trades
    # M - Market state payoffs 
    # mInd - Indicator for matched trades
    
    # Test by appending test trade  
    p = np.append(p,p_)
    q = np.append(q, q_)
    mInd = np.append(mInd, mInd_)
    tInd = np.append(tInd, tInd_)
    iMatched = np.append(iMatched, False)
    iUnmatched = np.logical_not(iMatched)
    
    # C, N = M.shape
    
    # Derived
    iTrader = tInd == tInd_
    iUnmatched = np.logical_not(iMatched)
    iOwnMatched = np.logical_and(iTrader, iMatched) 
    iOwnUnmatched = np.logical_and(iTrader, iUnmatched) 
    T = len(p)+1 # Number of trades
    D = tInd.max() # Number of traders
    Q = np.tile(q, (D,1)).transpose() # Tiled quantity
    IM = ind2vec(mInd-1).transpose() # Indicator for market
    IQ = ind2vec(tInd-1) # Indicator for trader
    Qstar = np.multiply(Q,IQ)
    Pstar = np.tile(p, (C,1))
    Mstar = np.matmul(M, IM)

    # Matched and unmatched collateral
    NC_matched = np.matmul((Mstar[:, iOwnMatched] - Pstar[:, iOwnMatched]), Qstar[iOwnMatched,:])
    NC_unmatched = np.matmul((Mstar[:, iOwnUnmatched] - Pstar[:, iOwnUnmatched]), Qstar[iOwnUnmatched,:])
    # Collateral check
    colChk = np.all(NC_matched + np.min(NC_unmatched, axis=0) + 2 >= 0)
    return colChk, NC_matched, NC_unmatched

In [433]:
def addTrade(p_, q_, mInd_, tInd_, p, q, mInd, tInd, iMatched, M):
    sigChk = True

    if sigChk:
        colChk = checkCollateral(p_, q_, mInd_, tInd_, p, q, mInd, tInd, iMatched, M)
        if colChk:
            p = np.append(p, p_)
            q = np.append(q, q_)
            mInd = np.append(mInd, mInd_)
            tInd = np.append(tInd, tInd_)
            iMatched = np.append(iMatched, False)
            iUnmatched = np.logical_not(iMatched)
            # Find a match
            matchInd = np.where(np.logical_and(np.logical_and(p == p_, (q == -q_)), iUnmatched)
            if matchInd:
                iMatched[matchInd] = True
                iMatched =  np.append(iMatched, True)
                return True
            else:
                iMatched =  np.append(iMatched, False)
                return False
        


In [425]:
# Inputs

# Current state
M = np.matrix([[0, 1], [1, 0],[0,0], [1, 1]]) # Market corners
# C, N = M.shape
p = np.array([0.5, 0.4, 0.9])
q = np.array([1, 2, -1])
mInd = np.array([1,2,2])
tInd = np.array([1, 1, 2])
iMatched = np.array([True, True, True])

# New trade
p_ = 0.5
q_ = -4
mInd_ = 1
tInd_ = 2
# Indicators



In [426]:
c, nc_m, nc_u = checkCollateral(p_, q_, mInd_, tInd_, p, q, mInd, tInd, iMatched, M)

In [431]:
nc_m + np.min(nc_u, axis=0)

matrix([[ 0. , -2.1],
        [ 0. , -1.1],
        [ 0. , -1.1],
        [ 0. , -2.1]])

In [442]:
np.where([True, True, False])[0][1]


1

In [390]:
q

array([ 1,  2, -1, -1])

In [314]:
mInd[matchInd]

array([1])

In [231]:
(p[iUnmatched] == p_) 

array([False,  True, False])

In [435]:
np.array([])

array([], dtype=float64)

False

In [1]:
b'abd'

b'abd'

In [3]:
'sig'.encode('utf-8') == b'sig'

True